= Constraining Data

TypeDB allows additional constraints to be defined on the types in the schema.
These constraints can restrict the cardinality of an interface, or the domain of values of an attribute-type.

== Cardinality constraints
Cardinality constraints restrict the number of interfaces of a specific type that may be attached to an instance.
These are specified using the annotation `@card(x..[y])`, where `x` is the minimum number permitted, and `y` is the maximum number. `y` may be omitted to not enforce an upper limit.

E.g. We can restrict a `friendship` relation to relate exactly two `friends`.
[,typeql]
----
friendship relates friend @card(2);
----

We can also restrict the number of roles of a specific type an instance plays, or the number of attributes of a specific type it owns.
E.g. A person can be involved in at most one employment, but own any number of emails.
[,typeql]
----
person plays employment:employee @card(0..1);
person owns email @card(0..);
----

=== Cardinality constraints on specialisation
Cardinality constraints declared on an interface applies to all instances of that interface (including specialisations).
A specialisation of an interface can also "tighten" the constraint.
e.g.
[,typeql]
----
relation sports-team,
    relates player @card(11);
relation football-team sub sports-team,
    relates goal-keeper as player @card(1),
    relates defender as player,
    relates midfielder as player,
    relates forward as player;
----
Here, a `sports-team` is constrained to have exactly 11 players.
`football-team` is a subtype of sports-team, and the various positions are specialisations of the `player` role.
Since all positions of are specialisations of `player`, it is enforced that a football team has 11 players across
whatever may be the distribution across the positions.
Additionally, the `@card(1)` ensures a team has exactly one `goal-keeper`.

The easiest way to reason about the effects of multiple constraints that apply to the same interface is
to apply them separately and ensure each of them is satisfied.

For the sake of the example, let's restrict our `football-team` to the more common distribution across positions.
[,typeql]
----
relation football-team sub sports-team,
    relates goal-keeper as player @card(1),
    relates defender as player @card(3..5),
    relates midfielder as player @card(3..5),
    relates forward as player @card(1..3);
----
The cardinality restrictions on the individual positions do not rule out a "(1-)4-5-3" formation,
but the `@card(11)` constraint on the `player` does.

==== On specialisation of implementations
Similarly, cardinality constraints on `plays` & `owns` can be specialised. e.g.:
[,typeql]
----
attribute name, value string;
attribute first-name sub name;
attribute last-name sub name;
entity animal owns name @card(0..3);
entity person sub animal,
    owns first-name @card(1..),
    owns last-name @card(1..);
----

=== `@unique` and `@key`
These are special cardinality constraints which can be applied to ownerships.

`owner owns attribute @unique` constrains a given `attribute` instance to be owned by at most one `owner` instance.

`owner owns attribute @key` requires every `owner` instance to own exactly one instance of the `attribute` type.
Additionally, the `@unique` constraint applies, requiring an `attribute` instance to be owned by at most one `owner` instance.


== Attribute value constraints
Attribute types may be annotated with constraints to restrict the values that an instance may hold. This allows an extra level of validation to be built into the schema.

* `@values(<value1>, ...)`: requires values to be one of those specified.
* `@range(<min>..<max>)`: requires values of numeric or time value types to lie within a range.
* `@regex(<regex>)`: requires values of string types to match the regex.

Value constraints are inherited by subtypes. A subtype may add its own value constraints to the inherited ones.
An instance of the subtype must satisfy all such declared & inherited value constraints.


== Other constraints
* `@abstract` prevents the type from being instantiated
// Other?

== Reference
* xref:{page-version}@typeql::annotations/index.adoc[Annotations]