= Entities, Relations, Attributes
// TODO: Out links to manual / fundamentals articles

TypeDB implements the Polymorphic Entity-Relation-Attribute (PERA) data model.
A TypeDB schema defines a hierarchy of these types, and how they interact with each other through interface-types.

=== Entity

Entities are standalone types, which exist independent of other types.

E.g. A `person` exists, regardless of whether they are involved in friendships or have a name.
[,typeql]
----
entity person;
----

=== Relation
Relations are types which define one-or-more associated interface types called "role".
The relation "depends" on other types in the schema to implement these interfaces by "playing" these roles.

E.g. An `employment` relation exists to relate an `employer` to an `employee`.
An `employment` instance cannot exist without the other instances which play these roles,
hence the idea that `employment` "depends" on the participating player types.
[,typeql]
----
relation employment, relates employer, relates employee;
----

=== Attribute
Attributes are types which hold a value. An attribute type must specify the primitive `value-type` of the values it will hold
An instance of an attribute type is identified by its value.

E.g. Any instance which has an age of 10 will refer to the same instance of the `age` attribute type.

[NOTE]
====
An attribute declares an implicit ownership interface.
A type can be defined to implement this interface using the `owns` keyword.
====

[,typeql]
----
attribute age, value integer;
----

== Owning attributes & playing roles

Entity & relation types may be defined to "own" attribute types.
Unlike attributes, which are identified by their values - there is no direct way to reference an entity.
Hence, entities (or relations) are referenced through their attributes.

E.g. A `person` may own an attribute `birth-date`, or an `employment` may own a `start-date`;
[,typeql]
----
person owns age;
----

Entity & relation types may be defined to "play" a role defined by a relation.

E.g. The entity type `company` may play the  `employer` role of an `employment` relation.

[,typeql]
----
company plays employment:employer;
----

== Polymorphism

Polymorphism in TypeDB is realised in two ways:

=== Interfaces
Multiple types may "implement" the same interface - i.e. play the same role, or own the same attribute.

In the following schema snippet, the `employer` role in the `employment` relation can be played by a `company` or an `charity`.

[,typeql]
----
define
  relation employment,
    relates employer,
    relates employee;

  entity company sub organisation,
    plays employment:employer;
  entity charity sub organisation,
    plays employment:employer;
----

Here, the role `employer` is the interface declared by the `employment` type. The `company` and `charity` types implement the interface.
The `relates` keyword is used to define the new role-type interface.
The `plays` keyword is used to implement a role-type interface.

=== Subtyping
TypeDB follows a single-inheritance *subtyping* system which allows types to specialize an existing type.
The subtype "inherits" all owns or plays implementations from its supertype.
Thus, an instance of the subtype may be used at any interface or function argument that accepts an instance of its super-type.

In the following schema snippet, entities of type `company` or `charity` can play the `employer` in an `employment`,
although it is their supertype `organisation` which is defined to play the role.

[,typeql]
----
define
  relation employment,
    relates employer,
    relates employee;

  entity organisation sub profile,
    plays employment:employer;
  entity company sub organisation;
  entity charity sub organisation;
----

==== Inheriting & specialising interfaces
A subtype also inherits any interfaces defined by its supertype.
It may optionally "specialise" an inherited interface by defining a subtype of that interface.

In the following schema snippet, `content-engagement` inherits the `content` role from `interaction` as-is, and "specialises" the inherited `subject` role into the `author` role.

[,typeql]
----
define
relation interaction @abstract,
    relates subject,
    relates content;
relation content-engagement @abstract, sub interaction,
    relates author as subject;
----

[NOTE]
====
An attribute type inherits and implicitly specialises the interface of its supertype.
====

// TODO:
// ==== Specialising interface implementations
// When a type implements a specialisation of an interface, the inherited implementation (if any) is hidden.
//
// E.g.
// [,typeql]
// ----
// ----