= Query Variables and Patterns

TypeQL is a declarative language -
Its focuses on describing the schema, data or query through *patterns*,
rather than specifying how to perform the query.
A [[definition-pattern]]*pattern* is a conjunction of any number of:

* constraints
* negated patterns
* optional patterns
* disjunctions of patterns


== Constraints
The unit of a pattern is a [[definition-constraint]]*constraint* between one or more *concepts*.
A [[definition-concept]]*concept* is a type, an instance of a type, or a value.

The concepts in a constraint can be specified directly, as we do when defining the schema:
[,typeql]
----
define
    entity person;      # 'person' is an entity type.
    attribute name;     # 'name' is an attribute type.
    name value string;  # 'name' holds string values.
    person owns name;   # 'person' instances can own 'name' instances
----

Or, we can use [[definition-variable]]*variables* as placeholders for concepts,
and query the database for concepts which "match" the pattern.
[,typeql]
----
match               # Find $e and $n such that:
    entity $e;        # $e is an entity type.
    attribute $n;     # $n is an attribute type.
    $n value string;  # $n holds string values.
    $e owns $n;       # $e instances can own instances of '$n'
----


Since *instances* cannot be specified directly,
constraints involving them always have variables which are then bound via pattern-matching.
Attributes are easily specified through constraints on their type and value.
[,typeql]
----
match   # match $n, $p, $e to concepts such that:
  # $n is a 'name' with value "John"
  $n isa name; $n == "John";

  # $p is a `person`, who has the attribute $n
  $p isa person; $p has $n;

  # $e is an 'employment', where '$p' plays the 'employee' role
  $e isa employment; $e links (employee: $p);
----

== Pattern matching & inserts
What does it mean to [[definition-match]]"*match*" a pattern?
A simple pattern is a conjunction of constraints, usually involving variables.
Put simply, a pattern is satisfied if each variable can be mapped to some concept
so every constraint holds true in the database.

Each such mapping from variables to concepts is an [[definition-answer]]*answer* to the pattern.
For the query above, each answer maps `$e` to an entity-type, and `$a` to an attribute-type owned by that type.
TypeDB will return all such mappings which satisfy the pattern.

// TODO: Do we want to break it down like this:
//  * All constraints on or between types are satisfied
//  * Each instance (& link) satisfies the typing constraints on it.
//  * Every instance, attribute ownership and relation-player link is in the database.


=== Insert

TypeQL uses the same patterns to describe the data being inserted as it does to query data.
The difference is that a `match` clause matches the patterns against the database and binds the variables to the matching concepts,
whereas an `insert` clause specifies the concepts to bind to the variables, and creates those patterns in the database.

Notice the above query & comments fit naturally:
[,typeql]
----
insert # Insert the concepts $n, $p, $e such that:
  # $n is a 'name' with value "John"
  $n isa name; $n == "John";

  # $p is a `person`, who has the attribute $n
  $p isa person; $p has $n;

  # $e is an 'employment', where '$p' plays the 'employee' role
  $e isa employment; $e links (employee: $p);
----

[NOTE]
====
Variables are also bound to concepts when they are inserted by an `isa` constraint.
See xref:{page-version}@new_core_concepts::typeql/schema-vs-data.adoc[]
====

==  Variables
Before we discuss combining constraints, we need a quick overview of the current variable visibility rules:

Variable names are unique within a pipeline (except when `select` clauses are used).
Conceptually an answer  is in

Further, TypeDB requires that a


== Disjunctions, negations & optionals
This section discusses the meaning of disjunctive, negated, and optional patterns.
It also discusses visibility of variables present in each of these sub-patterns.


[NOTE]
====
A `select` statement will free up all names except those of the selected variables.
This is an exception to the uniqueness of variables roles within a pipeline.
====

* an answer only contains variables which are guaranteed to be bound by the query - i.e. present in ALL execution paths of the query.


We use the following data as our running example:
[,typeql]
----
insert
    $james isa person, has name "James", has username "@james";
    $typedb isa company, has name "TypeDB", has username "@typedb";
    $emp isa employment, links (employer: $typedb, employee: $james);

    $john isa person, has name "John", has username "@john";
    $sky-high isa school, has name "Sky High School", has username "@sky-high";
    $edu isa education, links (institute: $sky-high, attendee: $john);

    $jeff isa person, has name "Jeff", has username "@jeff";

    $shut-shop isa company, has name "Shut Shop", has username "@shut-shop";
----

=== Disjunctions
Patterns can be combined in a disjunction using the `or` keyword.
An answer to any pattern in the disjunction is an answer to the disjunction.

Variables which are present in only some of the branches of a disjunction
(and not present outside the disjunction) are considered "local" to the pattern, and not included in the answer.

----
match
$p isa person, has name $p-name;
{
    $emp isa employment, links (employer: $company, employee: $p);
    $company has name $org-name;
} or
{
    $edu isa education, links (institute: $institute, attendee: $p);
    $institute has name $org-name;
};
----

Here, `$emp, $company, $edu, $institute` are local to their patterns.
`$p` occurs outside the disjunction.
`$org-name` is present in every-branch and returned by the disjunction.

The query returns:
[,]
----
    ---------------
    $p        | isa person, iid 0x1e00030000000000000004
    $p-name   | isa name John
    $org-name | isa name Sky High School
    ---------------
    $p        | isa person, iid 0x1e00030000000000000005
    $p-name   | isa name James
    $org-name | isa name TypeDB
    ---------------
Finished. Total rows: 2
----

[NOTE]
====
TODO: Disjoint variable usage
====

=== Negations
A pattern is negated by wrapping it in a `not` block.
An answer satisfies the negation iff it cannot be (part of) an answer to the negated pattern.
This resembles the "negation as failure" idea from logic programming.

Variables that are present only inside the negation are considered local to the negation.
Any variable that is present both outside and inside the negation is considered input to the negation.
[,typeql]
----
match
    $p isa person, has name $p-name;
    not {
        $e isa employment, links (employer: $c, employee: $p);
    };
----
Here, we find persons who are not involved in any `employment` relation with an `employer`.
`$p` is an input to the negation. `$e, $c` are local.
The query returns any person who is not involved in any employment.

The query returns:
----
   -------------
    $p-name | isa name Jeff
    $p      | isa person, iid 0x1e00030000000000000007
   -------------
    $p      | isa person, iid 0x1e00030000000000000004
    $p-name | isa name John
   -------------
Finished. Total rows: 2
----

As a second example, consider the query below:
[,typeql]
----
match
    $p isa person, has name $p-name;
    $c isa company, has name $c-name;
    not {
        $e isa employment, links (employer: $c, employee: $p);
    };
----
Here, `$c` is also an input variable.
This query finds pairs of `person` & `company` such that the person does not work at the company.

----
   -------------
    $p      | isa person, iid 0x1e00030000000000000004
    $p-name | isa name John
    $c      | isa company, iid 0x1e00050000000000000002
    $c-name | isa name TypeDB
   -------------
    $p      | isa person, iid 0x1e00030000000000000007
    $p-name | isa name Jeff
    $c      | isa company, iid 0x1e00050000000000000002
    $c-name | isa name TypeDB
   -------------
    $p      | isa person, iid 0x1e00030000000000000004
    $p-name | isa name John
    $c      | isa company, iid 0x1e00050000000000000003
    $c-name | isa name Shut Shop
   -------------
    $p      | isa person, iid 0x1e00030000000000000005
    $p-name | isa name James
    $c      | isa company, iid 0x1e00050000000000000003
    $c-name | isa name Shut Shop
   -------------
    $p      | isa person, iid 0x1e00030000000000000007
    $p-name | isa name Jeff
    $c      | isa company, iid 0x1e00050000000000000003
    $c-name | isa name Shut Shop
   -------------
Finished. Total rows: 5
----

=== Optionals
A pattern is made optional by wrapping it in a `try` block.
A variable that occurs only inside a `try` block is an optional variable.
The other variables can be considered input to the pattern.

If an optional pattern does match the data, it returns an answer per match.
If it has no matches, it produces a single answer with every optional variable bound to `None`.
[,typeql]
----
match
    $p isa person, has name $p-name;
    try {
        $e isa employment, links (employer: $c, employee: $p);
        $c has name $c-name;
    };
----
Here, `$e, $c, $c-name` are optional variables.
`$p` is input to the optional pattern.

The query returns:
[,typeql]
----
   -------------
    $p      | isa person, iid 0x1e00030000000000000005
    $p-name | isa name James
    $e      | isa employment, iid 0x1f00090000000000000002
    $c      | isa company, iid 0x1e00050000000000000002
    $c-name | isa name TypeDB
   -------------
    $p      | isa person, iid 0x1e00030000000000000004
    $p-name | isa name John
    $e      |
    $c      |
    $c-name |
   -------------
    $p      | isa person, iid 0x1e00030000000000000007
    $p-name | isa name Jeff
    $e      |
    $c      |
    $c-name |
   -------------
Finished. Total rows: 3
----

== Reference
* Constraints: xref:{page-version}@typeql::statements/index.adoc[typeql/statements]
* Disjunctions, Negations, optionals: xref:{page-version}@typeql::statements/index.adoc[typeql/patterns]

TODO: Decide if we want this section. I should probably introduce the ideas of type-inference.

=== Variable categories
Each constraint expects each of its concepts to be of a certain *category*.
For example, `<left> owns <right>` expects `<left>` to be an entity-type or a relation-type,
and the `<right>` to be an attribute-type.
We

[,typeql]
----
<EntityType> sub <EntityType>
<RelationType> sub <RelationType>
<AttributeType> sub <AttributeType>
<EntityType|RelationType> owns <AttributeType>
<RelationType> relates <RoleType>
<EntityType|RelationType> plays <RoleType>
<EntityType|RelationType|AttributeType> label <label>

<Entity> isa <EntityType>
<Relation> isa <RelationType>
<Attribute> isa <AttributeType>
<Entity|Relation> has <Attribute>
<Relation> links (<RoleType>: <Entity|Relation>)

<Attribute|Value> <COMPARATOR> <Attribute|Value>
let <Value> = <Expression<Attribute|Value>>
let <Instance|Value> in <FUNCTION>(<Instance|Value>, ...)
----

