= Schema & Data

As seen in the xref:{page-version}@new_core_concepts::typeql/entities-relations-attributes.adoc[] page, a TypeDB schema defines
a hierarchy of types, their associated interfaces and interfaces they implement.

__Data__ is created by instantiating types from the schema. As a result, it's impossible to create data not conforming to the types declared to the schema. Connections made between instances are also checked against the `owns`, `plays`, and `relates` in the schema to ensure it conforms to the permitted expressions of data.

As a result, TypeDB always guarantees semantic integrity of the database through type-checking and validation of data against the schema during writes.

== Inserting data
The TypeQL `insert` clause is used to insert new instances, the attributes owned by these instances, and the relations linking them.

=== Inserting new instances
New instances are inserted using an `isa` constraint specifying the type.
To insert an attribute, its value must also be specified.

[,typeql]
----
insert
  $person isa person;
  $employment isa employment;
  $age isa age 10;
----

Inserting a new instance will fail if the type is abstract. In the case of attributes,
the value must also be of the value-type specified by the attribute,
and satisfy all value constraints defined on the type.

Unlike entities, relations & attributes are not standalone types.
We will see how to create ownerships for attributes & link role-players to relations.

=== Inserting ownerships

An ownership between an entity (or relation) and an attribute is inserted using a `has` constraint:
[,typeql]
----
insert
  $person isa person;
  $age isa age 10;
  $person has $age;
----

Or in one line:
[,typeql]
----
insert $person isa person, has age 10;
----

This insert succeeds only if the type `person` "owns" the type `age` in the schema.
i.e. the constraint `person owns age;` was defined in the schema,
or `person` inherits `owns age` from its supertype.

[NOTE]
====
Unless declared `@independent`, attributes which are not involved in any ownerships will be cleaned up at the end of a transaction.
====

=== Linking role-players

Since relations exist to "link" instances together,
these links between the relation are role-players are typically inserted along with the relation:
[,typeql]
----
insert
  $company isa company;
  $person isa person;
  $employment isa employment;
  $employment links (employer: $company);
  $employment links (person: $person);
----

The `isa` and `links` can be written together:
[,typeql]
----
insert
  # ...
  $employment isa employment,
    links (employer: $company, employee: $person);
----

There's an even shorter version if you prefer:
[,typeq]
----
insert
  # ...
  $employment isa employment (employer: $company, employee: $person);
----

Inserting `$employment links (employer: $company)` succeeds only if
the type `company` plays the `employer` role defined by the `employment` relation.
Similarly, the type `person` must play the `employment:employee` role
for `$employment links (person: $person);` to be inserted.


// == TODO: Decide if the following sections are relevant:
//
// == Commit-time validation & schema migrations
// Most constraints are validated when the data is mutated, giving strong integrity guarantees at all times.
// However, to remain flexible enough to allow more elaborate mutations which can't be expressed in a single query,
// TypeDB defers validating certain constraints (such as cardinality) to commit-time.
// This is especially relevant in the context of schema migrations, which we see next.
// The committed state of the database will always be consistent fully with the schema.
//
// === Schema mutations with data in-place
// TypeDB's approach to schema mutations is to choose a path that modifies the database
// in a way that the data remains consistent with the schema at all times.
// To illustrate, consider
