= TypeDB Studio

TypeDB Studio is an interactive visual environment for managing and querying TypeDB databases.

With Studio, developers can efficiently manage databases, execute queries, and explore query results,
all within a unified environment.

TypeDB Studio is available both as a web app and as a desktop application. All features of TypeDB Studio
are available on both web and desktop. Be aware that the web app may not be able to connect to non-HTTPS endpoints (e.g. localhost, 127.0.0.1) on certain browsers; at the time of writing, Chrome works, but Safari does not.

[cols-2]
--
.https://studio.typedb.com[Visit studio.typedb.com]
[.clickable]
****
Launch TypeDB Studio in your web browser.
****

.https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name:%5Etypedb-studio[Install TypeDB Studio Desktop,window=_blank]
[.clickable]
****
Download TypeDB Studio for desktop.
****

.link:https://github.com/typedb/typedb-studio/[GitHub,window=_blank]
[.clickable]
****
Browse the source code of TypeDB Studio.
****
--

== TypeDB Studio User Manual

For connection instructions and usage guides, see:

[cols-2]
--
.xref:{page-version}@tools::studio.adoc[TypeDB Studio User Manual]
[.clickable]
****
How to use TypeDB Studio.
****
--
