= Lesson 10: Using inference
:page-aliases: {page-version}@academy::10-  using-functions/overview.adoc
:page-preamble-card: 1

In this lesson, we'll learn how to write and use rules effectively. We'll start by seeing how rules can be used like views in order to *abstract complex query patterns* into more maintainable forms. Then we'll explore how we can use rules to build networks of logic, covering *rule chaining* and *rule branching*, allowing us to create complex behaviour from simple rules. As part of this, we'll also examine *rule recursion*.

== Recommended prerequisites

* You should complete xref:{page-version}@academy::8-composing-clauses/index.adoc[Lesson 8] before starting this lesson.

== Lesson contents

[cols-2]
--
.xref:{page-version}@academy::10-  using-functions/10.1-functions-as-views.adoc[]
[.clickable]
****
Learn how to create simple abstractions for complex patterns.
****

.xref:{page-version}@academy::10-  using-functions/10.2-function-chaining.adoc[]
[.clickable]
****
Learn how to chain rules, into each other and recursively.
****
