= Troubleshooting

This section provides general recommendations and solutions to common issues faced while interacting with TypeDB.

Please refer to the section closest to your problem.
If you cannot find a solution, do not hesitate to send us a message on https://discord.com/channels/665254494820368395/983769458269114408[Discord]!

[cols-2]
--
.xref:{page-version}@maintenance-operation::troubleshooting/installation.adoc[]
[.clickable]
****
Addressing setup issues.
****

.xref:{page-version}@maintenance-operation::troubleshooting/connection.adoc[]
[.clickable]
****
Resolving connection issues.
****

.xref:{page-version}@maintenance-operation::troubleshooting/stopping-queries.adoc[]
[.clickable]
****
Query takes too long.
****

--

== Other links

[cols-2]
--
.xref:{page-version}@guides::typeql/debugging-typeql.adoc[Guide for debugging TypeQL]
[.clickable]
****
Debug queries using TypeQL's composability.
****

.xref:{page-version}@guides::typeql/optimizing-typeql.adoc[Guide for optimizing TypeQL]
[.clickable]
****
Write efficient queries using optimization techniques.
****
--
