= Lesson 3.4: Fetching schema types

== Variablizing types

So far, we've seen that the output of Fetch queries includes a `type` field for every retrieved data instance and their attributes. However, there are also types involved in the query that are not returned. Consider this polymorphic query from xref:{page-version}@academy::3-reading-data/3.2-fetching-polymorphic-data.adoc[Lesson 3.2], where we asked for books that a user had interacted with in some way on the web store.

[,typeql]
----
match
$user isa user, has id "u0008";
$book isa book;
action-execution (executor: $user, action: $action);
$rel links ($book, $action);
fetch {
  "isbn": $book.isbn,
  "title": $book.title
};
----

[,json]
----
{
  "title": "Electron Backscatter Diffraction in Materials Science",
  "isbn": [
    "9780387881355",
    "0387881352"
  ]
}
{
  "isbn": [
    "9780060929794",
    "0060929790"
  ],
  "title": "One Hundred Years of Solitude"
}
{
  "isbn": [
    "9780008627843",
    "0008627843"
  ],
  "title": "The Hobbit"
}
{
  "isbn": [
    "9780500026557",
    "0500026556"
  ],
  "title": "Hokusai's Fuji"
}
{
  "isbn": [
    "9780008627843",
    "0008627843"
  ],
  "title": "The Hobbit"
}
{
  "title": "Classical Mythology",
  "isbn": [
    "9780195153446",
    "0195153448"
  ]
}
----

While the results list the books, they do not tell us anything about the nature of the user's interaction with them. We can easily retrieve this information by adding a couple of additional lines to the query.

[,typeql]
----
match
$user isa user, has id "u0008";
$book isa book;
action-execution (executor: $user, action: $action);
$rel links ($book, $action);
$action isa! $action-type;   # new line
fetch {
  "isbn": [ $book.isbn ],
  "title": $book.title,
  "action-type": $action-type
};
----


If we run this new query, we now also retrieve the type of `$action`!

[,json]
----
{
  "title": "Electron Backscatter Diffraction in Materials Science",
  "isbn": [
    "9780387881355",
    "0387881352"
  ],
  "action-type": {
    "kind": "entity",
    "label": "order"
  }
}
{
  "isbn": [
    "9780060929794",
    "0060929790"
  ],
  "title": "One Hundred Years of Solitude",
  "action-type": {
    "kind": "entity",
    "label": "order"
  }
}
{
  "title": "The Hobbit",
  "action-type": {
    "kind": "entity",
    "label": "order"
  },
  "isbn": [
    "9780008627843",
    "0008627843"
  ]
}
{
  "action-type": {
    "kind": "entity",
    "label": "review"
  },
  "title": "Hokusai's Fuji",
  "isbn": [
    "9780500026557",
    "0500026556"
  ]
}
{
  "isbn": [
    "9780008627843",
    "0008627843"
  ],
  "action-type": {
    "kind": "entity",
    "label": "review"
  },
  "title": "The Hobbit"
}
{
  "action-type": {
    "kind": "entity",
    "label": "review"
  },
  "isbn": [
    "9780195153446",
    "0195153448"
  ],
  "title": "Classical Mythology"
}
----

We have been able to retrieve this information by introducing a new `$action-type` variable in an additional statement.

[,typeql]
----
$action isa! $action-type;
----

Here we've used the `isa!` keyword which, like the `isa` keyword, is used to specify the type of a variable. However, while the `isa` keyword simultaneously matches a type and all of its subtypes, the `isa!` keyword matches a type _exactly_, without using inheritance polymorphism. We will see more examples of this throughout this lesson and later in the course.

Previous `isa` statements we've used have used a variable as the https://en.wikipedia.org/wiki/Subject%E2%80%93verb%E2%80%93object_word_order[subject] of the statement and a *type label* as the https://en.wikipedia.org/wiki/Subject%E2%80%93verb%E2%80%93object_word_order[object], but in this `isa!` statement we've also used a variable, `$action-type`, as the object. The `isa` and `isa!` keywords must always take a data instance as the subject and a type as the object, which means that the variable `$action-type` represents a type rather than a data instance! Here we've made use of *type variablization*, one of TypeQL's most powerful features.

[#_exercise_3_4_1]
.Exercise
[caption=""]
====
Modify the above query to also retrieve the type of the relation between `$book` and `$action`.

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
$user isa user, has id "u0008";
$book isa book;
(executor: $user, action: $action) isa action-execution;
$rel isa! $relation-type, links ($book, $action);
$action isa! $action-type;
fetch {
  "isbn": [$book.isbn],
  "title": $book.title,
  "action-type": $action-type,
  "relation-type": $relation-type,
};
----

=====
====


// This section is omitted due to the difficulty of retrieving exact roles.
// See: https://github.com/typedb/typedb/issues/6986#issuecomment-1948116205
// == Variablizing roles
//
// The ability to variablize types in queries arises from TypeQL's core philosophy:
//
// [quote]
// ____
// https://typedb.com/fundamentals/type-theory[_Everything has a type, and so everything can be a variable._]
// ____
//
// In fact, every element of `match` clauses in TypeQL queries can be variablized except for the keywords. This means that we can also take advantage of *role variablization*. In the following query, we retrieve a list of contributors to a particular book.
//
// [,typeql]
// ----
// match
// $book isa book, has isbn "9780500026557";
// $contributor isa contributor;
// $contribution (work: $book, contributor: $contributor) isa contribution;
// fetch
// $contributor: name;
// ----
//
//
// [,json]
// ----
// {
//     "contributor": {
//         "name": [ { "value": "Wada, Kyoko", "value_type": "string", "type": { "label": "name", "root": "attribute" } } ],
//         "type": { "label": "contributor", "root": "entity" }
//     }
// }
// {
//     "contributor": {
//         "name": [ { "value": "Katsushika, Hokusai", "value_type": "string", "type": { "label": "name", "root": "attribute" } } ],
//         "type": { "label": "contributor", "root": "entity" }
//     }
// }
// ----
//
// However, the results do not tell us how each person contributed to the book. To retrieve this information, we can replace the role name `contributor` with a variable.
//
// [,typeql]
// ----
// match
// $book isa book, has isbn "9780500026557";
// $contributor isa contributor;
// $contribution (work: $book, $contributor-role: $contributor) isa contribution;
// fetch
// $contributor: name;
// $contributor-role;
// ----
//
//
// [,json]
// ----
// result placeholder
// ----
//
// Now we can see each contributor's role in the results! When not part of a relation tuple, roles are described by *role labels*, comprising two terms specified by a `:` delimiter. The first term is the name of the relation that the role is part of, and the second is the name of the role in the scope of the relation. This is because multiple relations are permitted to use the same role names. So, for instance, the label `authoring:author` represents the `author` role of the `authoring` relation type.
//
// This tells us something important about the results we have been retrieving: the `contribution` relations the query has matched are not all of the same type. The `contribution` relation type actually has three subtypes: `authoring`, `editing`, and `illustrating`, and we have been matching all of them using inheritance polymorphism!
//
// .Exercise
// [caption=""]
// ====
// Modify the solution to the <<#_exercise_3_4_1,last exercise>> to also retrieve the roles that `$book` and `$action` play in the variablized relation.
//
// .Sample solution
// [%collapsible]
// =====
// [,typeql]
// ----
// match
// $user isa user, has id "9780500026557";
// $book isa book;
// (executor: $user, action: $action) isa action-execution;
// ($book-role: $book, $action-role: $action) isa! $relation-type;
// $action isa! $action-type;
// fetch
// $book: isbn, title;
// $action-type;
// $relation-type;
// $book-role;
// $action-role;
// ----
//
// =====
// ====

== Querying type hierarchies

In addition to using type variablization to retrieve the types of data instances returned in our queries, we can also query the schema directly, without having to involve data instances at all. For example, the following query retrieves the subtypes of `book`.

[,typeql]
----
match $book_type sub book;
fetch { "book-type" : $book_type };
----


[,json]
----
{ "book-type": { "kind": "entity", "label": "book" } }
{ "book-type": { "kind": "entity", "label": "hardback" } }
{ "book-type": { "kind": "entity", "label": "paperback" } }
{ "book-type": { "kind": "entity", "label": "ebook" } }
----

These are indeed the subtypes of `book`. We also retrieve the type `book` itself because it is trivially its own subtype. For this query, we've used the `sub` keyword, which matches subtypes of a given supertype. Unlike the `isa` keyword, both the subject and the object of `sub` statements must be *types*. In this case, we've variablized the subject of the `sub` statement to query subtypes, but we could also variablize the object to query supertypes. In the following example, we query the supertypes of `publisher`.

[,typeql]
----
match publisher sub $supertype;
fetch { "supertype" : $supertype };
----


[,json]
----
{ "supertype": { "kind": "entity", "label": "company" } }
{ "supertype": { "kind": "entity", "label": "publisher" } }
----

If we would like to retrieve only _direct_ subtypes or supertypes of a type, we can instead use the `sub!` keyword, similar to the `isa!` keyword!

[,typeql]
----
match publisher sub! $supertype;
fetch { "supertype" : $supertype };
----


[,json]
----
{ "supertype": { "kind": "entity", "label": "company" } }
----

.Exercise
[caption=""]
====
Write a query to retrieve the direct supertype of `city`.

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
city sub! $supertype;
fetch {
  "supertype": $supertype,
};
----

=====

Now write a query to determine the other types that share that direct supertype.

.Hint
[%collapsible]
=====
The query should retrieve the direct subtypes of `place`.
=====

.Sample solution
[%collapsible]
=====
[,typeql]
----
match $place_type sub! place;
fetch { "place-type" : $place_type };
----

=====

====

== Querying ownership interfaces

In addition to querying the type hierarchies defined in the schema, we can also query the defined *ownership* and *role* interfaces. In the following query, we retrieve the list of attribute types that the entity type `promotion` owns.

[,typeql]
----
match promotion owns $attribute;
fetch { "attribute-type": $attribute };
----

[,json]
----
{ "attribute-type": { "kind": "attribute", "label": "code", "valueType": "string" } }
{ "attribute-type": { "kind": "attribute", "label": "name", "valueType": "string" } }
{ "attribute-type": { "kind": "attribute", "label": "start-timestamp", "valueType": "datetime" } }
{ "attribute-type": { "kind": "attribute", "label": "end-timestamp", "valueType": "datetime" } }
----

To query ownerships, we use the `owns` keyword. As with the `sub` keyword, we can invert the intent of the statement by variablizing the object instead of the subject. We do this in the next query to retrieve the list of types that own the attribute type `isbn-13`.

[,typeql]
----
match $type owns isbn-13;
fetch { "type" : $type };
----

[,json]
----
{ "type": { "kind": "entity", "label": "book" } }
{ "type": { "kind": "entity", "label": "hardback" } }
{ "type": { "kind": "entity", "label": "paperback" } }
{ "type": { "kind": "entity", "label": "ebook" } }
----

.Exercise
[caption=""]
====
Write a query to retrieve the list of types that own `name`.

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
$type owns name;
fetch {
  "owner": $type,
}
----

=====
====

== Querying role interfaces

Ownerships of attribute types are queried using a single keyword `owns`, but roles in relations must be queried using two different keywords: `relates` and `plays`. We will see how they work in the next few examples. To begin with, we will use the `relates` keyword to retrieve the list of roles in the `locating` relation.

[,typeql]
----
match locating relates $role;
fetch { "role" : $role };
----

[,json]
----
{ "role": { "kind": "relation:role", "label": "locating:located" } }
{ "role": { "kind": "relation:role", "label": "locating:location" } }
----


// Temporarily changed to reflect above redaction of role variablization section.
When not part of a relation tuple, roles are described by *role labels*, comprising two terms specified by a `:` delimiter. The first term is the name of the relation that the role is part of, and the second is the name of the role in the scope of the relation. This is because multiple relations are permitted to use the same role names. So, for instance, the label `locating:located` represents the `located` role of the `locating` relation type.
// As we saw previously, role labels are denoted using both the name of the parent relation and the scoped name of the role.

To query for types that play a role using the `plays` keyword, we must use the same notation.

[,typeql]
----
match $type plays locating:located;
fetch { "type" : $type };
----

[,json]
----
{ "type": { "kind": "entity", "label": "publication" } }
{ "type": { "kind": "entity", "label": "user" } }
{ "type": { "kind": "entity", "label": "address" } }
{ "type": { "kind": "entity", "label": "place" } }
{ "type": { "kind": "entity", "label": "city" } }
{ "type": { "kind": "entity", "label": "state" } }
{ "type": { "kind": "entity", "label": "country" } }
----

Here we have queried the types that play the `located` role in `locating`. As with the `sub` and `owns` keywords, we can also invert the intent of `plays` [#_footnote_1]#statements#^<<_footnotes,1>>^. In the next query, we do so in order to retrieve the list of roles that `book` plays.

[,typeql]
----
match book plays $role;
fetch { "role" : $role };  
----

[,json]
----
{ "role": { "kind": "relation:role", "label": "contribution:work" } }
{ "role": { "kind": "relation:role", "label": "publishing:published" } }
{ "role": { "kind": "relation:role", "label": "promotion-inclusion:item" } }
{ "role": { "kind": "relation:role", "label": "order-line:item" } }
{ "role": { "kind": "relation:role", "label": "rating:rated" } }
{ "role": { "kind": "relation:role", "label": "recommendation:recommended" } }
----

.Exercise
[caption=""]
====
Write a query to retrieve the list of roles in the `delivery` relation.

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
delivery relates $role;
fetch {
  "role": $role,
};
----

=====

Now modify the query to also retrieve the types that play those roles.

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
delivery relates $role;
$type plays $role;
fetch {
  "role": $role,
  "player": $type,
};
----

=====
====

[#_footnotes]
== Footnotes

1. <<_footnote_1,^>> The astute reader will notice that we have used this "inversion" technique for `sub`, `owns`, and `plays` statements, but not for `relates` statements. TypeQL is flexible enough that we could certainly do so if we wanted, but it is not particularly useful to and there are certain practical considerations that make the syntax tricky to use correctly. While learning the basics of TypeQL, it is best to avoid `relates` statements of this kind.
