= Lesson 7.3: Logical operators

== Disjunctions

By default, all statements in a pattern are joined in a https://en.wikipedia.org/wiki/Logical_conjunction[conjunction]. As we have seen in xref:{page-version}@academy::7-understanding-query-patterns/7.1-patterns-as-constraints.adoc[Lesson 7.1], this means that the pattern must be satisfied as a set of simultaneous constraints.

If we want to create a https://en.wikipedia.org/wiki/Logical_disjunction[disjunction], we must do so explicitly, as we do in the following Fetch query where we retrieve a list of books that a user "likes". We consider a user to have liked a book if either they have ordered it _or_ they have reviewed it with a score of seven or higher.

[,typeql]
----
match
$user isa user, has id "u0008";
$liked-book isa book;
{
    action-execution ($user, $order);
    order-line ($order, $liked-book);
} or {
    action-execution ($user, $review);
    rating ($review, $liked-book);
    $review has score >= 7;
};
fetch {
  "isbn-13": $liked-book.isbn-13,
};
----

As in programming languages, we call the patterns inside one set of `{}` **blocks**. Variables defined in a parent block are "shared" with the child block, the same way scoping works in programming languages. Variables defined in every branch of the disjunction are also shared with the parent scope.

To construct a disjunction within a query pattern, we place make each branch of the disjunction a separate block and interleave the blocks with the `or` keyword.

[,typeql]
----
{
    # branch 1
} or {
    # branch 2
};
----

In this example, we have used a disjunction with two branches, but they can be made to have any number by extending the syntax. The final block of a disjunction must be followed with a `;` delimiter, signalling the end of the disjunction. As with all TypeQL syntax elements, whitespace and indentation does not affect the functionality of a disjunction.

.Exercise
[caption=""]
====
Write a Fetch query to retrieve the ISBN-13s of all books that are included in an order that has a status of "paid", "dispatched", or "delivered".

You may find it useful to refer to the bookstore's schema.

.Schema
[%collapsible]
=====
[,typeql]
----
include::{page-version}@academy::attachment$bookstore-schema.tql[lines=19..]
----
=====

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
$book isa book;
$order isa order;
order-line ($book, $order);
{
    $order has status "paid";
} or {
    $order has status "dispatched";
} or {
    $order has status "delivered";
};
fetch {
  "isbn-13": $book.isbn-13,
};
----
=====
====

== Negations

Just as we can represent a disjunction of patterns, we can also represent the https://en.wikipedia.org/wiki/Negation[negation] of patterns. The following Fetch query retrieves a list of books that do not have illustrators.

[,typeql]
----
match
$book isa book;
not {
    ($book, $contributor) isa illustrating;
};
fetch {
  "isbn-13": book.isbn-13,
};
----

To construct a negation within a query, we place the negated pattern inside a block preceded by the `not` keyword and followed by a `;` delimiter.

[,typeql]
----
not {
    # negated pattern
};
----


[IMPORTANT]
====
All patterns inside a block must have at least one variable that is shared with the pattern outside the block. Additionally, variables that _only_ appear within a block cannot be accessed in other clauses of the query.
====

.Exercise
[caption=""]
====
Write a Fetch query to retrieve the ISBN-13s of books that the user with ID "u0008" has neither ordered nor reviewed, indicating that the book would likely be new to that user.

You may find it useful to refer to the bookstore's schema.

.Schema
[%collapsible]
=====
[,typeql]
----
include::{page-version}@academy::attachment$bookstore-schema.tql[lines=19..]
----
=====

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
$user isa user, has id "u0008";
$new-book isa book;
not {
    action-execution ($user, $order);
    order-line ($order, $new-book);
};
not {
    action-execution ($user, $review);
    rating ($review, $new-book);
};
fetch {
  "isbn-13": $new-book.isbn-13,
};
----

Here, we have used a conjunction of negations, but we could identically use a negation of disjunctions by https://en.wikipedia.org/wiki/De_Morgan%27s_laws[De Morgan's laws]!

[,typeql]
----
match
$user isa user, has id "u0008";
$new-book isa book;
not { {
    action-execution ($user, $order);
    order-line ($order, $new-book);
} or {
    action-execution ($user, $review);
    rating ($review, $new-book);
}; };
fetch {
  "isbn-13": $new-book.isbn-13,
};
----
=====
====

== Optionals

Optional patterns allow you to do **partial** matching. Patterns inside a `try` block must also *all* be matched (just like any conjunction). However, a `try` block's content that fail to match complete do not cause the outer pattern to fail.

[,typeql]
----
match
$ebook isa ebook;
try {
    $ebook has isbn-10 $isbn;
};
fetch {
  "isbn-10": $isbn,
};
----

To construct a negation within a query, we place the negated pattern inside a block preceded by the `ty` keyword and followed by a `;` delimiter.

[,typeql]
----
try {
    # optional pattern
};
----

Variables only used inside of an optional clause are returned, but not available to sibling `try`, `not`, or `or` clauses.

== Identities

We encountered the following query in xref:{page-version}@academy::3-reading-data/3.5-query-validation.adoc[Lesson 3.5], in which we have used the `is` keyword. It retrieves the IDs of orders being sent to a city other than the city of the user that placed the order.

[,typeql]
----
match
locating (located: $user, location: $user-city);
action-execution (action: $order, executor: $user);
delivery (delivered: $order, destination: $destination);
locating (located: $destination, location: $destination-city);
$user-city isa city;
$destination-city isa city;
not { $destination-city is $user-city; };
fetch {
  "order-id": $order.id,
};
----

The `is` keyword is used to denote that two variables are identical: that they represent the **same** data object. It is most useful when used in a negation, in order to state that two variables are _not_ identical. The distinction with a `==`, is that `==` performs equality by __value__ only: meaning an attribute `age 10` and `year 10` would be equal by `==`, but not using `is`.

.Exercise
[caption=""]
====
Write a Fetch query to retrieve the ISBN-13s of pairs of books that have the same publisher, along with the name of the shared publisher.

You may find it useful to refer to the bookstore's schema.

.Schema
[%collapsible]
=====
[,typeql]
----
include::{page-version}@academy::attachment$bookstore-schema.tql[lines=19..]
----
=====

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
$book-1 isa book;
$book-2 isa book;
$shared-publisher isa publisher;
publishing ($book-1, $shared-publisher);
publishing ($book-2, $shared-publisher);
not { $book-1 is $book-2; };
fetch {
  "isbn-1": $book-1.isbn-13,
  "isbn-2": $book-2.isbn-13,
  "publisher": $shared-publisher.name,
};
----

If we did not state that `$book-1` and `$book-2` are not identical, then this query would be trivially satisfied by retrieving all books, which always have the same publishers as themselves! Try running it with and without the negation statement to see this.
=====
====
