= Lesson 7.4: Value comparisons
:page-preamble-card: 1

TypeQL provides several operators for comparing the values of attributes and literals in patterns.

Equality operators:: `==`, `!=`
Ordering operators:: `>`, `>=`, `<`, `\<=`
String matching operators:: `contains`, `like`
Concept equality: `is`

We have already seen a few examples of them in previous lessons.

== Equality operators

The equality operators are valid for comparing *values* of all value types. We can compare the values of attributes either to those of literals or to those of each other. In the following Fetch query, we retrieve a list of books that were published in a city other than New York.

[,typeql]
----
match
$book isa book;
($book, $publication) isa publishing;
($publication, $city) isa locating;
$city isa city, has name != "New York City";
fetch {
  "isbn": $book.isbn-13,
};
----

In this next query, we retrieve pairs of books that were published in the same year.

[,typeql]
----
match
$book-1 isa book;
$book-2 isa book;
publishing ($book-1, $publication-1);
publishing ($book-2, $publication-2);
$publication-1 isa publication, has year $year-1;
$publication-2 isa publication, has year $year-2;
not { $book-1 is $book-2; };
$year-1 == $year-2;
fetch {
  "isbn-1": $book-1.isbn-13,
  "isbn-2": $book-2.isbn-13,
};
----

== Ordering operators

The ordering operators can be used to compare any value type. We have already seen an example of their use in xref:{page-version}@academy::7-understanding-query-patterns/7.3-logical-operators.adoc[Lesson 7.3], where we retrieved a list of books that a user has eiter ordered or reviewed with a score of seven or higher.

[,typeql]
----
match
$user isa user, has id "u0008";
$liked-book isa book;
{
    action-execution ($user, $order);
    order-line ($order, $liked-book);
} or {
    action-execution ($user, $review);
    rating ($review, $liked-book);
    $review has score >= 7;
};
fetch {
  "isbn": $liked-book.isbn-13,
};
----

In this next query we retrieve a list of books that have a retail price under $15.

[,typeql]
----
match
$book isa book, has price <= 15.00;
fetch {
  "isbn": $book.isbn-13,
  "title": $book.title,
  "price": $book.price,
};
----

.Exercise
[caption=""]
====
Write a Fetch query to retrieve the IDs of orders that were placed during the Holiday Sale 2023. The entity representing this sale has the code "HOL23".

You may find it useful to refer to the bookstore's schema.

.Schema
[%collapsible]
=====
[,typeql]
----
include::{page-version}@academy::attachment$bookstore-schema.tql[lines=19..]
----
=====

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
$holiday-order isa order;
action-execution ($holiday-order),
    has timestamp $order-time;
$holiday-sale isa promotion,
    has code "HOL23",
    has start-timestamp <= $order-time,
    has end-timestamp >= $order-time;
fetch {
  "order-id": $holiday-order.id,
};
----
=====
====

[NOTE]
====
The ordering operators are also valid for strings, use https://en.wikipedia.org/wiki/Lexicographic_order[lexicographic ordering].
====

== String matching operators

TypeQL includes two operators for string matching, denoted by the keywords `contains` and `like`. The `contains` operator checks if one string contains another in a case-insensitive manner, while the `like` operator can be used to match strings through Regex. Unlike the equality and ordering operators, the string matching operators can only be used to compare attribute values to string literals; they cannot be used to compare the values of two attributes.

The following query uses the `contains` operator to retrieve a list of books with both "electron" and "diffraction" in the title.

[,typeql]
----
match
$book isa book, has title $title;
$title contains "electron";
$title contains "diffraction";
fetch {
  "title": $book.title,
};
----

[,json]
----
{
  "title": "Electron Backscatter Diffraction in Materials Science"
}
{
  "title": "Interpretation of Electron Diffraction Patterns"
}
----

[WARNING]
====
For non-Latin characters, the case insensitivity of the `contains` operator can result in https://en.wikipedia.org/wiki/Dotted_and_dotless_I_in_computing[unexpected behaviour].
====

Meanwhile, the following query uses the `like` operator to retrieve a list of books whose titles start with "the".

[,typeql]
----
match
$book isa book, has title like "(?i)^the\s.*";
fetch {
  "title": $book.title,
};
----

_Note: in Console, you might have to escape the `\` as `\\`_

[,json]
----
{
  "title": "The Complete Calvin and Hobbes"
}
{
  "title": "The Hitchhiker's Guide to the Galaxy"
}
{
  "title": "The Hobbit"
}
{
  "title": "The Iron Giant"
}
{
  "title": "The Motorcycle Diaries: A Journey Around South America"
}
{
  "title": "The Mummies of Urumchi"
}
{
  "title": "The Odyssey"
}
----

.Exercise
[caption=""]
====
Write a Fetch query to retrieve the titles of books that contain "the" in a position other than the start.

You may find it useful to refer to the bookstore's schema.

.Schema
[%collapsible]
=====
[,typeql]
----
include::{page-version}@academy::attachment$bookstore-schema.tql[lines=19..]
----
=====

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
$book isa book, has title like "(?i).+\sthe\s.*";
fetch {
  "title": $book.title,
};
----
=====

Write a Fetch query to retrieve the ISBN-13s of all books that are included in an order that has a status of "paid", "dispatched", or "delivered", without using a disjunction (note: this is less performant than using a disjunction!)

.Sample solution
[%collapsible]
=====
[,typeql]
----
match
$book isa book;
$order isa order;
order-line ($book, $order);
$order has status like "^(paid|dispatched|delivered)$";
fetch {
  "isbn": $book.isbn-13,
};
----
=====
====
