= Advanced Queries
:title: Quickstart advanced queries
:test-typeql: linear
// :test-python: yes
// :test-rust: yes
:experimental:
:tabs-sync-option:

In the previous sections you:

. Set up a TypeDB server and accessed your preferred tool (Studio or Console)
. Created a database and defined a schema
. Loaded some data using simple write and more complex read-write queries

In this page we'll look at a few other types of clauses, and how clause chaining can be generalised into query _pipelines_.
We'll then also meet _functions_, which are re-usable pieces of queries that can even do things like recursion.

Finally, we'll meet the `fetch` clause, which lets you format your data into JSON and look up additional information for each answer before returning them.


== Delete & Reduce

Let's look at two more useful clauses: `delete`, `reduce`.

=== Delete

We know how to create data and read data, but what if we want to remove data?

Deletion uses a different syntax from insertion and matching in order to specifically pinpoint what data to delete.

[tabs]
====
Studio::
+
--

Let's delete the user with username "candice001":

[,typeql]
----
#!test[write, db=quickstart]
include::./advanced-queries.adoc[tag=delete1]
----

Easy enough! What if we wanted to delete an owned attribute?

We need a variable to hold the username, then we can remove it - let's remove the start-date of the friendship between "alice1925" and "bob78":

[,typeql]
----
#!test[write, db=quickstart]
include::./advanced-queries.adoc[tag=delete2]
----

Notice how deletes specify "what" to delete, and "where" to delete that from.

--
Console::
+
--

Let's delete the user with username "candice001":

////
[,typeql]
----
# tag::delete1[]
match
$user isa user, has username "candice001";
delete $user;
# end::delete1[]
----
////
[,typeql]
----
#!test[write, db=quickstart]
include::./advanced-queries.adoc[tag=delete1]
----

Easy enough! What if we wanted to delete an owned attribute?

We need a variable to hold the username, then we can remove it - let's remove the start-date of the friendship between "alice1925" and "bob78":
////
[,typeql]
----
# tag::delete2[]
match
$u0 isa user, has username "alice1925";
$u1 isa user, has username "bob78";
$friendship isa friendship ($u0, $u1),
  has start-date $start-date;
delete
$start-date of $friendship;
# end::delete2[]
----
////
[,typeql]
----
#!test[write, db=quickstart]
include::./advanced-queries.adoc[tag=delete2]
----

Notice how deletes specify "what" to delete, and "where" to delete that from.

--
====

=== Reduce

The `reduce` clause works by collapsing the answers provided by a query using an aggregation operation, such as `count` or `sum`.

[tabs]
====
Studio::
+
--

Using a read transaction, let's count the number of users in the database:

[,typeql]
----
#!test[read, db=quickstart]
include::./advanced-queries.adoc[tag=reduce1]
----

We see the following result:
[source]
----
------------
$count | 5
------------
----

Notice that the user variable `$user` has been consumed by the `reduce` and we created a new variable `$count`!

Reductions can also use `groupby` to apply an aggregation within a grouping:

[,typeql]
----
#!test[read, db=quickstart]
include::./advanced-queries.adoc[tag=reduce2]
----

[source]
----
------------------
$num-friends | 1
$user        | isa user, iid 0x1e00000000000000000007
$username    | isa username fizzbuzz
------------------
$num-friends | 1
$user        | isa user, iid 0x1e00000000000000000006
$username    | isa username ecclestone
------------------
$num-friends | 1
$user        | isa user, iid 0x1e00000000000000000001
$username    | isa username bob78
------------------
$num-friends | 1
$user        | isa user, iid 0x1e00000000000000000000
$username    | isa username alice1925
------------------
$num-friends | 2
$user        | isa user, iid 0x1e00000000000000000005
$username    | isa username deltaonenine
----------------------
----

Here we see the number of friends for each user, grouped by unique pairs of (user, username).
Of course, we know that each user has a unique username!

Notice that the variables in the grouping have not been consumed by the `reduce` clause and are returned in the results.

--
Console::
+
--

////
[,typeql]
----
# tag::reduce1[]
match
$user isa user;
reduce $count = count;
# end::reduce1[]
----
////
[,typeql]
----
#!test[write, db=quickstart]
include::./advanced-queries.adoc[tag=reduce1]
----

We see the following result:
[source]
----
------------
$count | 5
------------
----

////
[,typeql]
----
# tag::reduce2[]
match
$user isa user, has username $username;
friendship ($user, $friend);
reduce $num-friends = count groupby $user, $username;
# end::reduce2[]
----
////
[,typeql]
----
#!test[write, db=quickstart]
include::./advanced-queries.adoc[tag=reduce2]
----

[source]
----
------------------
$num-friends | 1
$user        | isa user, iid 0x1e00000000000000000007
$username    | isa username fizzbuzz
------------------
$num-friends | 1
$user        | isa user, iid 0x1e00000000000000000006
$username    | isa username ecclestone
------------------
$num-friends | 1
$user        | isa user, iid 0x1e00000000000000000001
$username    | isa username bob78
------------------
$num-friends | 1
$user        | isa user, iid 0x1e00000000000000000000
$username    | isa username alice1925
------------------
$num-friends | 2
$user        | isa user, iid 0x1e00000000000000000005
$username    | isa username deltaonenine
----------------------
----

Here we see the number of friends for each user, grouped by unique pairs of (user, username).
Of course, we know that each user has a unique username!

Notice that the variables in the grouping have not been consumed by the `reduce` clause and are returned in the results.

--

====

If this feels familiar, that's probably because you've met `reduce` operations in programming languages!
Often these are applied to collections of data, such as lists, or structures like iterators or streams.

**A good mental model of TypeQL queries is that any clause produces a stream of answers, which is either returned or processed by the next clause.**

This is a very powerful tool for composing queries, as we'll see next!

== Chaining clauses into pipelines

We'd like to write a query that does the following:

Make every user friends with the most popular user in the database, if they aren't already friends.

Conceptually, this requires three steps:

. Find the most popular user in the database
. Find all users that aren't friends with the most popular user
. Make those users friends with the most popular user

We can build this query, one part at a time, by chaining together query clauses into one extended _query pipeline_.

Let's start with the first step:

[tabs]
====
Studio::
+
--

To solve this, we'll build on top of the `reduce` query we wrote previously:
the most popular user is the one with the highest number of friends - we'll sort the `reduce` results by number of friends, and limit to the first answer.

Let's meet two new operations: `sort` and `limit`.
We call these query stream **operators** as opposed to clauses since they only manipulate the answer that stream from the previous clause.

At this point we can construct a query **pipeline**, made up of **clauses** and **operators**.
We can generically refer to clauses and operators as **stages** in the pipeline:
a pipeline is made up stages, which are either clauses or operators.

[,typeql]
----
#!test[read, db=quickstart]
include::./advanced-queries.adoc[tag=pipeline1]
----

Which returns:
[source]
----
------------------
$num-friends | 2
$user        | isa user, iid 0x1e00000000000000000006
$username    | isa username deltaonenine
------------------
----

Perfect! We've identified the most popular user.

--
Console::
+
--

To solve this, we'll build on top of the `reduce` query we wrote previously:
the most popular user is the one with the highest number of friends - we'll sort the `reduce` results by number of friends, and limit to the first answer.

Let's meet two new operations: `sort` and `limit`.
We call these query stream **operators** as opposed to clauses since they only manipulate the answer that stream from the previous clause.

At this point we can construct a query **pipeline**, made up of **clauses** and **operators**.
We can generically refer to clauses and operators as **stages** in the pipeline:
a pipeline is made up stages, which are either clauses or operators.

////
[,typeql]
----
# tag::pipeline1[]
match
$user isa user, has username $username;
friendship ($user, $friend);
reduce $num-friends = count groupby $user, $username;
sort $num-friends desc;
limit 1;
# end::pipeline1[]
----
////
[,typeql]
----
#!test[read, db=quickstart]
include::./advanced-queries.adoc[tag=pipeline1]
----
Which returns:
[source]
----
------------------
$num-friends | 2
$user        | isa user, iid 0x1e00000000000000000006
$username    | isa username deltaonenine
------------------
----

Perfect! We've identified the most popular user.

--
====

Next we'll add another clause to find users that aren't friends with this user:

[tabs]
====
Studio::
+
--

This time we use a `not` statement to filter out users that are already friends with the most popular user,
and also to eliminate the most-popular user from appearing again:

[,typeql]
----
#!test[read, db=quickstart]
include::./advanced-queries.adoc[tag=pipeline2]
----

This returns:
[source]
----
------------------
$num-friends | 2
$other-user  | isa user, iid 0x1e00000000000000000001
$user        | isa user, iid 0x1e00000000000000000006
$username    | isa username deltaonenine
------------------
$num-friends | 2
$other-user  | isa user, iid 0x1e00000000000000000002
$user        | isa user, iid 0x1e00000000000000000006
$username    | isa username deltaonenine
------------------
----

We're almost there! We just need to add a stage to create friendship between the most popular user and the users we found.

--
Console::
+
--

This time we use a `not` statement to filter out users that are already friends with the most popular user,
and also to eliminate the most-popular user from appearing again:

////
[,typeql]
----
# tag::pipeline2[]
match
$user isa user, has username $username;
friendship ($user, $friend);
reduce $num-friends = count groupby $user, $username;

sort $num-friends desc;
limit 1;

match
$other-user isa user;
not { $user is $other-user; };
not { friendship ($user, $other-user); };
# end::pipeline2[]
----
////
[,typeql]
----
#!test[read, db=quickstart]
include::./advanced-queries.adoc[tag=pipeline2]
----

This returns:
[source]
----
------------------
$num-friends | 2
$other-user  | isa user, iid 0x1e00000000000000000001
$user        | isa user, iid 0x1e00000000000000000006
$username    | isa username deltaonenine
------------------
$num-friends | 2
$other-user  | isa user, iid 0x1e00000000000000000002
$user        | isa user, iid 0x1e00000000000000000006
$username    | isa username deltaonenine
------------------
----

We're almost there! We just need to add a stage to create friendship between the most popular user and the users we found.

--
====

Let's stack one more `insert` clause to create the desired friendships.
Note that this means this query now is a write query, and requires a write transaction.

[tabs]
====
Studio::
+
--

[,typeql]
----
#!test[write, db=quickstart]
include::./advanced-queries.adoc[tag=pipeline3]
----

After you've executed the query once, every user will be friends with the most popular user!

--
Console::
+
--

////
[,typeql]
----
# tag::pipeline3[]
match
$user isa user, has username $username;
friendship ($user, $friend);
reduce $num-friends = count groupby $user, $username;
sort $num-friends desc;
limit 1;

match
$other-user isa user;
not { $user is $other-user; };
not { friendship ($user, $other-user); };

insert
friendship ($other-user, $user);
# end::pipeline3[]
----
////
[,typeql]
----
#!test[write, db=quickstart]
include::./advanced-queries.adoc[tag=pipeline3]
----

After you've executed the query once, every user will be friends with the most popular user!

--
====

Fantastic! We've got a singe query that will: identify the most popular user,
identify all users that aren't friends with the most popular user,
and create friendships between the most popular user and the users we found.

Pipelines are a very powerful tool for composing queries. They are easy to read and understand,
since the data flow is explicit in the order of the query stages.

At the same time, query pipelines are very easy to debug: truncate your pipeline at any point
and inspect the intermediate results by executing the truncated query.

== Functions

In the query we just wrote, we might want to re-use the "find the most popular user" part of the query pipeline.

We can do this by declaring a function, which can be committed to the database as part of the schema.

Note that functions can contain full query pipelines, but cannot have side effects (eg. must be read-only).

[tabs]
====
Studio::
+
--

[,typeql]
----
#!test[schema, db=quickstart]
include::./advanced-queries.adoc[tag=function1]
----

This function returns the first user and username using the same logic as the long pipeline we just wrote,
with a tiebreaker on the username if there are multiple "most popular users".

Don't forget to commit so the function becomes available outside the transaction!

--
Console::
+
--

////
[,typeql]
----
# tag::function1[]
define

# note: if there are multiple "most popular users", tiebreak on the username
fun most_popular_user() -> user, username:
  match
  $user isa user, has username $username;
  friendship ($user, $friend);
  reduce $num-friends = count groupby $user, $username;
  sort $num-friends desc, $username asc;
  return first $user, $username;

# end::function1[]
----
////
[,typeql]
----
#!test[schema, db=quickstart]
include::./advanced-queries.adoc[tag=function1]
----

This function returns the first user and username using the same logic as the long pipeline we just wrote,
with a tiebreaker on the username if there are multiple "most popular users".

Don't forget to commit so the function becomes available outside the transaction!
--
====

Now we can invoke the function in a pipeline.

Let's try to find the users who are friends with our popular user:

[tabs]
====
Studio::
+
--

[,typeql]
----
#!test[schema, db=quickstart]
include::./advanced-queries.adoc[tag=function_pipeline1]
----

This query is now very short, since we've re-used the logic from the function to find the most popular user!

--
Console::
+
--

////
[,typeql]
----
# tag::function_pipeline1[]
match
let $most-popular-user, $most-popular-username = most_popular_user();
$other-user isa user, has username $username;
not { $most-popular-user is $other-user; };
friendship ($other-user, $most-popular-user);
# end::function_pipeline1[]
----
////
[,typeql]
----
#!test[read, db=quickstart]
include::./advanced-queries.adoc[tag=function_pipeline1]
----

This query is now very short, since we've re-used the logic from the function to find the most popular user!

--
====

Congratulations!
You're now ready to write sophisticated yet modular queries!

One last topic, which makes incorporating TypeDB into your applications easier:
formatting TypeDB answers into JSON, and incorporating additional data into JSON responses.

== Fetch

TypeQL features one special clause: `fetch`.
This clause can only be used at the end of a pipeline.

Fetch converts a standard TypeDB answer into a JSON document. You can use it to organize the data into a specific structure,
look up additional attributes, and even execute subqueries and nest their answers into the JSON document.

The `fetch` clause structure is designed to look exactly like the JSON document it will return, let's take a look:


[tabs]
====
Studio::
+
--

[,typeql]
----
#!test[schema, db=quickstart]
include::./advanced-queries.adoc[tag=fetch1]
----

This query now returns a sequence of JSON documents:
[source]
----
{
  "friends": [
    {
      "friend": "bob78"
    }
  ],
  "username": "alice1925"
}

{
  "friends": [
    {
      "friend": "alice1925"
    }
  ],
  "username": "bob78",
}

{
  "friends": [
    {
      "friend": "ecclestone"
    },
    {
      "friend": "fizzbuzz"
    }
  ],
  "username": "deltaonenine"
}
----

The fetch clause lets you lay out precisely the JSON document you need for your application,
and makes it easy to retrieve additional data like (possibly absent) attributes or answers from subqueries.

--
Console::
+
--

////
[,typeql]
----
# tag::fetch1[]
match
$user isa user;
limit 3;
fetch {
  # get the username if it exists - if not, the JSON value will be set to null
  "username": $user.username,

  # run a subquery, and collect the answers into a list value
  "friends": [
    match
    $other-user isa user;
    friendship ($user, $other-user);
    fetch {
      "friend": $other-user.username
    };
  ]
};
# end::fetch1[]
----
////
[,typeql]
----
#!test[read, db=quickstart]
include::./advanced-queries.adoc[tag=fetch1]
----

The fetch clause lets you lay out precisely the JSON document you need for your application,
and makes it easy to retrieve additional data like (possibly absent) attributes or answers from subqueries.

--
====

== What next?
There is much more to explore in the world of TypeDB, including building custom query logic using disjunctions and negations, the deep exploration of data connection using functional recursion, and more.

This is the beginning of your journey, and we’d like to be here for you should you have any question - so do not hesitate to reach out!
