= `@abstract` annotation
:page-aliases: {page-version}@reference::typeql/statements/abstract.adoc
:test-typeql: linear

The `@abstract` annotation is used
// tag::overview[]
to specify that a type is abstract.
// end::overview[]

== Syntax

.Syntax
[,typeql]
----
<type label> @abstract;
----

The `@abstract` annotation does not accept any arguments.

== Usage

// tag::description[]
When defined for a type, the `@abstract` annotation enforces the `abstract` constraint, making the type abstract.
An abstract type cannot be instantiated, but can be used in a query (e.g., in an `isa` constraint to match instances of its subtypes).
// end::description[]

[,typeql]
----
include::{page-version}@reference::example$tql/schema_annotations.tql[tags=define-keyword;abstract-entity;]
----

=== Subtyping

The `abstract` constraint is not inherited.
This means all subtypes of an abstract type are concrete by default, enabling the creation of their instances.
However, it is possible to define an abstract subtype of an abstract type.

[,typeql]
----
#!test[schema]
include::{page-version}@reference::example$tql/schema_annotations.tql[tags=define-keyword;abstract-attribute]
----

It is impossible to define an abstract subtype of a concrete type.

.Wrong definition!
[,typeql]
----
#!test[schema, fail_at=runtime]
define
  attribute categorized-username @abstract, sub username;
----

=== Specialization of role types

// TODO: Add a hyperlink to "relates as"
Similarly, abstract role types cannot be instantiated.
A concrete sub role type can be defined using **specialization** (keyword `as`).

[,typeql]
----
#!test[schema]
include::{page-version}@reference::example$tql/schema_annotations.tql[tags=define-keyword;abstract-relation]
----
