= Delete stage
:page-aliases: {page-version}@reference::typeql/queries/delete.adoc
:test-typeql: linear

A delete stage deletes data from the database. Deletable data includes instances of types, ownerships of attributes, and role players of
relations.

== Syntax

The body of a delete stage is a sequence of delete statements.

[,typeql]
----
delete
    ( <variable> | has <variable> of <variable> | links ( <variable> [ , ... ] ) of <variable> );
    [ ... ]
----

== Behavior

* Bare variables delete the instances they refer to from the database. 
* xref:{page-version}@reference::typeql/statements/has.adoc[Delete has statements] delete ownerships of attributes.
* xref:{page-version}@reference::typeql/statements/links.adoc[Delete links statements] delete role players from relations.

== Execution

The delete stage must be preceded by other stages. The body of the delete stage is executed once for each input row. The output is then a
stream of input rows with the deleted concepts removed.

== Example

.Schema for the following examples
[%collapsible]
====
[,typeql]
----
#!test[schema, commit]
include::{page-version}@reference::example$tql/schema_statements_functions.tql[tags=define-keyword;entities;attributes;relation-group]
----
====

[,typeql]
----
#!test[write]
match
  $user isa user, has name "<name>";
  $group isa group, has group-id "<group id>";
  $membership isa group-membership(group: $group, member: $user), has rank $rank;
  $rank == "member";
delete
  has $rank of $membership;
  links ($user) of $membership;
  $group;
----
