= Update stage
:page-aliases: {page-version}@reference::typeql/queries/update.adoc
:test-typeql: linear

An update stage updates data in the database. Updatable data includes ownerships of attributes and role players of
relations.

== Syntax

The body of an update stage is a sequence of update statements, which are similar to xref:{page-version}@reference::typeql/statements/has.adoc[`has`] and xref:{page-version}@reference::typeql/statements/links.adoc[`links`] statements of xref:{page-version}@reference::typeql/pipelines/insert.adoc[insert].

[,typeql]
----
update <update-statement> [ <update-statement> ... ]
----

== Behavior

* xref:{page-version}@reference::typeql/statements/has.adoc[Has statements] replace existing attribute ownerships of the specified attribute's type (xref:{page-version}@reference::typeql/statements/isa.adoc[`isa!`]) with a new ownership of the specified instance.
If an attribute is provided by value, the attribute type is mandatory.
* xref:{page-version}@reference::typeql/statements/links.adoc[Links statements] replace existing role players of the specified player's role (xref:{page-version}@reference::typeql/statements/isa.adoc[`isa!`]) with the specified instance.
Role tags can be omitted if there is only a single role the role player can play.

Update stages cannot bind new variables.

If there is no existing data to replace, the operation is equivalent to xref:{page-version}@reference::typeql/pipelines/insert.adoc[insert].

== Execution

The update stage must be preceded by other stages. The body of the update stage is executed once for each input row. In case multiple rows will update the same data, only the last update will persist. The output is then a stream equivalent to the input rows, as no variables are modified.

== Validation

Only unambiguous operations on xref:{page-version}@reference::typeql/statements/owns.adoc[`owns`] and xref:{page-version}@reference::typeql/statements/relates.adoc[`relates`] with xref:{page-version}@reference::typeql/annotations/card.adoc[cardinalities] limited by 1 are allowed.

The modified concepts are validated the same way as in xref:{page-version}@reference::typeql/pipelines/insert.adoc#_validation[insert stages].

== Example

.Schema for the following examples
[%collapsible]
====
[,typeql]
----
#!test[schema, commit]
include::{page-version}@reference::example$tql/schema_statements_functions.tql[tags=define-keyword;entities;attributes;relation-group]
----
====

[,typeql]
----
#!test[write]
match
  $group isa group, has group-id "<group id>";
  $user isa user, has username "<username>";
  $group-membership isa group-membership, has rank "admin", links (member: $user);
update
  $group-membership has rank "member";
  $group-membership links (group: $group);
----
