= Expressions
:page-aliases: {page-version}@typeql::expressions.adoc
:test-typeql: linear

A TypeQL expression uses operators and functions to
compute a value from other values. It uses the following syntax:
[,typeql]
----
let <var> = <expression>;
----
Examples:
[,typeql]
----
#!test[read]
match
let $x = 5;

let $y = $x * 3.1;

let $z = ceil($y + 1);
----

== Validation
The following rules apply to variables involved in expressions:

* The variables used on the right-hand side of an expression must be bound to either attributes or values.
* The attribute may be of various attribute types as long as they all have the same value type.
* A value variable must be assigned to exactly once.

During compilation, the types of every subexpression are resolved, and the expression tree is constructed.
If any function which is passed an argument which does not match the expected type,
or any operator which is not defined for the given combination of types, will fail compilation with an error.

== Explore expressions
[cols-3]
--
.xref:{page-version}@reference::typeql/expressions/literals.adoc[]
[.clickable]
****
Syntax for literal values in TypeQL.
****

.xref:{page-version}@reference::typeql/expressions/operators.adoc[]
[.clickable]
****
Arithmetic and other operators in TypeQL expressions.
****

.xref:{page-version}@reference::typeql/expressions/function-calls.adoc[]
[.clickable]
****
Calling functions in TypeQL expressions.
****
--
