= Negations
:page-aliases: {page-version}@reference::typeql/patterns/negation.adoc
:test-typeql: linear

Negations can be used to exclude certain subpatterns from your query results -
 an answer is excluded if it matches the subpattern.

== Syntax

[,typeql]
----
not { <pattern> };
----

The patterns inside a negated is called the *excluded pattern*.

[NOTE]
====
Like all patterns, negations can be chained, e.g.:
[,typeql]
----
not { <p1> };
not { <p2> };
----
which is equivalent to a negated disjunction `not { { <p1> } or { <p2> }; };`.

Since negations are themselves patterns, they can also be nested, e.g.:
[,typeql]
----
not {
  <p1>
  not { <p2> };
};
----
====

== Behavior

Negations may appear in `match` stages of data pipelines or functions, where they behave as follows.

* *Internal variables*. Variable whose scope lies inside an excluded pattern are not returned as part of the stage's output (i.e., such variables are xref:{page-version}@reference::typeql/data-model.adoc#modes[internal] variables).
* *Satisfaction*. A pattern with a negation will return those outputs which satisfy the pattern outside the negation, but do not satisfy the excluded pattern for _any_ choice of internal variables in that pattern.
* *Recursion*. When using recursive functions with negations, care needs to be taken that evaluation of the negation does not depend on the recursive function call itself (in other words, TypeDB works with https://en.wikipedia.org/wiki/Stratification_(mathematics)#In_mathematical_logic[stratified negation]).

== Examples

.Schema for the following examples
[%collapsible]
====
[,typeql]
----
#!test[schema, commit]
include::{page-version}@reference::example$tql/conjunction.tql[tags=patterns-schema]
----
====

. Retrieve users without friends
+
--
[,typeql]
----
#!test[read]
match
  $x isa user, has username $name;
  not { friendship($x, $y); };
----
--

. Retrieve users without friends that have no friends
+
--
[,typeql]
----
#!test[read]
match
  $x isa user, has username $name;
  not { friendship($x, $y);
    not { friendship($y, $z); };
  };
----
[NOTE]
====
Negated queries (especially nested negations) can become xref:{page-version}@maintenance-operation::troubleshooting/optimizing-queries.adoc[expensive].
====
--
