= Connections

== Overview

To interact with a TypeDB database, a client application must first establish a connection to the server. This is typically done using a
xref:{page-version}@core-concepts::drivers/index.adoc[TypeDB driver] for your chosen programming language (e.g., Python, Java, Rust, Node.js) or through a tool like the TypeDB Console or TypeDB Studio.

A connection requires the server's address (host and port) and valid user credentials. For production environments, a secure connection using
TLS is strongly recommended.

== Connecting to TypeDB

[tabs]
====
Studio::
+
--
For a cloud deployment:

// include::../tools/studio.adoc[tag=connect_cloud_studio]
. In the https://cloud.typedb.com[TypeDB Cloud website], navigate to your cluster and click *Connect*. Then, click *Connect with TypeDB Studio*. This will launch TypeDB Studio.
. Fill in your password and hit *Connect*. Your password can be found in your downloaded credentials file (if you have one).

For an Enterprise or Community Edition deployment:

// include::../tools/studio.adoc[tag=connect_enterprise_studio]
. Launch TypeDB Studio.
. Enter the address of the HTTP endpoint of your cluster. By default, this is at port 8000.
. Enter your username and password.
. Click `Connect`.
--
Console::
+
--
Run Console in CLI:

//include::../tools/console.adoc[tag=connect_console]
.Connect to TypeDB
[source,console]
----
typedb console --address=<server-address> --username=<username>
----

You will be prompted for a password.
--

====

=== Connecting your application

For programmatic access using gRPC, use one of the TypeDB xref:{page-version}@core-concepts::drivers/connections.adoc[driver to connect] via the network API.

All TypeDB Drivers follow the same API as closely as possible, so moving between languages is simple.

Some languages also have a helper driver library that abstracts away usage of the HTTP API. See the references pages for xref:{page-version}@reference::typedb-grpc-drivers/index.adoc[gRPC drivers] or the xref:{page-version}@reference::typedb-http-drivers/index.adoc[HTTP helper libraries]. You can also always use the xref:{page-version}@reference::typedb-http-api.adoc[raw HTTP api].

