= Create data
:pageTitle: Create data
:keywords: start, learn, typedb, typeql, tutorial, quickstart, console, studio, database, create, insert, query, schema
:summary: Use queries to load data into your database
:tabs-sync-option:
:test-typeql: linear

== Review

In the previous sections we've:

. xref:get_started/setup.adoc[] TypeDB and Studio (or Console)
. xref:get_started/schema.adoc[Created a schema]
.. Created a database called `get_started`.
.. Defined the social network schema:
+
[,typeql]
----
#!test[schema]
include::{page-version}@new_home::page$get_started/schema.adoc[tag=full_define]
----

== Overview

We are now ready to write data to our database. We'll see few examples of how we can create data,
and how TypeDB's type system enforces our data constraints when adding and modifying data.

== Pure insert queries

The most basic writes in TypeDB are pure insertions: they insert a complete bundle of data at once.

=== Entities and attributes

Let's create some entities and attributes with pure insertions.

////
[,typeql]
----
# tag::insert1[]
insert $u isa user;
# end::insert1[]

# tag::insert4[]
insert
$u0 isa user, has username "ziggy";
$u1 isa user, has username "ziggy";
# end::insert4[]

# tag::insert2[]
insert $u0 isa user, has username "alice";
# end::insert2[]

# tag::insert3[]
insert
$u1 isa user, has username "bob";
$u2 isa user;
$u2 has username "charlene";  # can split `isa` and `has` across different statements
# end::insert3[]

# tag::insert5[]
insert
$u3 isa user, has username "delta";
$u4 isa user, has username "echo";
$u5 isa user, has username "fizzbuzz";
friendship (friend: $u3, friend: $u4);
friendship (friend: $u3, friend: $u5);
# end::insert5[]
----
////

[tabs]
====
Studio::
+
--
To begin, set your transaction type to *write* using the top bar, then let us try and insert a user with the following `insert` query:

[,typeql]
----
include::./data.adoc[tag=insert1]
----
The commit **will fail** - an example of TypeDB enforcing data constraints!
(If you're manually controlling your transaction, you'll see the error when you click 'commit'.)

We are trying to insert a `user` without a username here, but we declared usernames to be a _key_ attribute earlier when we defined `user owns username @key`.

The following passes TypeDB's validation and commits just fine:

[,typeql]
----
include::./data.adoc[tag=insert2]
----

We can also insert multiple values in a single `insert` query like so:

[,typeql]
----
include::./data.adoc[tag=insert3]
----
This query inserts two users at the same time and also commits safely.

Finally, since we set usernames to be a `@key` attribute of our users, we would - rightfully - expect the following query to fail:

[,typeql]
----
include::./data.adoc[tag=insert4]
----

This will immediately cause the transaction to fail, as the server detects an invalid database state.

--

Console::
+
--

To begin, let us try insert a user with the following `insert` query:

[,typeql]
----
#!test[write, fail_at=commit]
include::./data.adoc[tag=insert1]
----

Submitting `commit` **will fail** - an example of TypeDB enforcing data constraints!

We are trying to insert a `user` without a username here, but we declared usernames to be a _key_ attribute earlier when we defined `user owns username @key`.

The following passes TypeDB's validation and `commit`s just fine:
[,typeql]
----
#!test[write]
include::./data.adoc[tag=insert2]
----

This query inserts two users at the same time:
[,typeql]
----
#!test[write]
include::./data.adoc[tag=insert3]
----

This query inserts two users at the same time.
Time to commit your queries again to safely persist your changes: type `commit` and press kbd:[Enter].

Finally, since we set usernames to be a `@key` attribute of our users, we would - rightfully - expect the following query to fail:
[,typeql]
----
#!test[write, fail_at=runtime]
include::./data.adoc[tag=insert4]
----

This will immediately cause the transaction to fail, as the server detects an invalid database state.

--

====

So far we've illustrated how we can insert simple entities with attributes, and how TypeDB keeps us accountable to follow the definitions in the database schema.

So far so good!

=== Complete relations

Now we've seen how to create entities and attributes - what about inserting relations?
Well, relations that are created at the same time as the connected role players are as easy as entities and attributes!

[tabs]
====
Studio::
+
--

In order to insert a friendship, we need to refer to users that will play the role of friends in the friendship.
That's where variables come into play!

[Note]
-----
Recall that each friendship takes exactly two friends as specified in the schema; feel free to experiment though, and see what error messages TypeDB will give you when trying to insert triple friendships.
-----

[,typeql]
----
include::./data.adoc[tag=insert5]
----

This query inserts three new users with some ``friendship``s between them.

The relations are using shorthand, and could themselves be written as `$f isa friendship (friend: $x, friend: $y);` if you'd want to further refer to them with the variable `$f`; but otherwise it's convenient to simply omit it.

Make sure your data is committed so we can use the friendships later!

--
Console::
+
--

In order to insert a friendship, we need to refer to users that will play the role of friends in the friendship.
That's where variables come into play!

[Note]
-----
Recall that each friendship takes exactly two friends as specified in the schema; feel free to experiment though, and see what error messages TypeDB will give you when trying to insert triple friendships.
-----

Using a new `write` transaction, run:

[,typeql]
----
#!test[write]
include::./data.adoc[tag=insert5]
----
This query inserts three new users with some ``friendship``s between them.

The relations are using shorthand, and could themselves be written as `$f isa friendship (friend: $x, friend: $y);` if you'd want to further refer to them with the variable `$f`; but otherwise it's convenient to simply omit it.

Type `commit` to persist your changes so we can use these friendships later!

--

====

This is great, but we won't always be creating new users and friendships from scratch.
We'll probably want to create friendships between existing users too!

That requires us to read existing data, and then execute write operations.

== Read-Write queries

Reading data in TypeDB happens with a `match` clause.
We'll then use the `insert` clause to connect the found data.

=== Reading data

Looking up data is easy - it looks a lot like inserting data.

Let's find some users and their information.

[tabs]
====
Studio::
+
--

Change the transaction type to *read* in the top toolbar, and execute the following query:

[,typeql]
----
include::./data.adoc[tag=match1]
----
This query returns the substitutions (answers) for each variable that exist in the database and conforms to the requested constraints:
any `user` instance that has a `username`!

We get back the following sets of values:

[source]
----
include::./data.adoc[tag=match1_result]
----

[NOTE]
=====
IIDs are "instance IDs". These are auto-generated unique IDs for each entity and relation.
Though fixed in each database, they are not necessarily deterministic across databases - your IIDs might be different!
=====

We can make this more specific and interesting, for instance looking up the friends that exist of a particular user:

[,typeql]
----
include::./data.adoc[tag=match2]
----

Which returns:
[source]
----
include::./data.adoc[tag=match2_result]
----

--
Console::
+
--

Open a read transaction using `transaction read get-started`, and execute the following query:

////
[,typeql]
----
# tag::match1[]
match $u isa user, has username $n;
# end::match1[]

# tag::match1_result[]
--------
$n | isa username "alice"
$x | isa user, iid 0x1e00000000000000000003
--------
$n | isa username "bob"
$x | isa user, iid 0x1e00000000000000000004
--------
$n | isa username "charlene"
$x | isa user, iid 0x1e00000000000000000005
--------
$n | isa username "delta"
$x | isa user, iid 0x1e00000000000000000006
--------
$n | isa username "echo"
$x | isa user, iid 0x1e00000000000000000007
--------
$n | isa username "fizzbuzz"
$x | isa user, iid 0x1e00000000000000000008
--------
# end::match1_result[]
----
////
[,typeql]
----
#!test[read, count=6]
include::./data.adoc[tag=match1]
----
This query returns the substitutions (answers) for each variable that exist in the database and conforms to the requested constraints:
any `user` instance that has a `username`!

We get back the following answers:

[source]
----
include::./data.adoc[tag=match1_result]
----

[NOTE]
=====
IIDs are "instance IDs". Though fixed in each database, These are auto-generated unique IDs for each entity and relation.
Though fixed in each database, they are not necessarily deterministic across databases - your IIDs might be different!
=====


We can make this more specific and interesting, for instance looking up the friends that exist of a particular user:

////
[,typeql]
----
# tag::match2[]
match
$user isa user, has username "echo";
$other-friend isa user, has username $other-username;
friendship ($user, $other-friend);
# end::match2[]

# tag::match2_result[]
---------------------
$other-friend   | isa user, iid 0x1e00000000000000000006
$other-username | isa username "delta"
$user           | isa user, iid 0x1e00000000000000000007
---------------------
# end::match2_result[]
----
////
[,typeql]
----
#!test[read, count=1]
include::./data.adoc[tag=match2]
----

Which returns:
[source]
----
include::./data.adoc[tag=match2_result]
----

We can `close` the transaction since we won't be using it anymore.
Closing transactions is good practice since they consume resources on the server.
--
====

As you can see, reading data using `match` clauses is easy:
simply describe what the data should conform to, and TypeDB will find all answers to your query from the database.

The order of statements in a `match` clause doesn't matter! This is one property that makes TypeQL extremely composable
and debuggable: **if your query isn't doing what you expect, just remove parts until it's simple enough to verify -
then build it back up bit by bit**!

=== Connecting existing data

Now that we know how to look data up - how do we use that to perform a query that creates a relation between existing data?

The key is that we can _chain_ an `insert` clause after a `match` clause.
The `insert` clause will receive the same set of variables and answers you would see printed out if you executed just the `match` clause!

Using this principle, let's:

. retrieve some users with a `match` clause.
. write a new `friendship` relation between those users with an `insert` clause.

Remember, you'll need a `write` transaction now since we're modifying data!

[tabs]
====
Studio::
+
--
[,typeql]
----
include::./data.adoc[tag=match-insert1]
----
Chained query clauses always execute in-order, so the direction you read in is how operations will be performed:
First we find two specific users by username, then insert a new friendship between them referring to those users using variables.

Feel free to insert more data, e.g., create a university and enrol some of your users in it using our `enrolment` relations!

Let's commit to save our new data!
--

Console::
+
--

////
[,typeql]
----
# tag::match-insert1[]
match
$x isa user, has username "alice";
$y isa user, has username "bob";
insert
friendship (friend: $x, friend: $y), has start-date 2015-01-01T00:00:00;
# end::match-insert1[]
----
////
[,typeql]
----
#!test[write, count=1]
include::./data.adoc[tag=match-insert1]
----
Chained query clauses always execute in-order, so the direction you read in is how operations will be performed:
First we find two specific users by username, then insert a new friendship between them referring to those users using variables.

Feel free to insert more data, e.g., create a university and enrol some of your users in it using our `enrolment` relations!

Let's commit to save our new data!
--
====

Pure inserts are generally used to create new entities and attributes -
all other operations require a `match` clause to find existing data to work with.
This applies to clauses like `delete` and `update` as well.

You can read more about other clause types in the applicable xref:{page-version}@new_core_concepts::typeql/query-clauses.adoc[Concepts page].

Here's the full set of queries you've used to succesfully write data into TypeDB:
[,typeql]
----
include::{page-version}@new_home::page$get_started/data.adoc[tag=insert2]

include::{page-version}@new_home::page$get_started/data.adoc[tag=insert3]

include::{page-version}@new_home::page$get_started/data.adoc[tag=insert5]

include::{page-version}@new_home::page$get_started/data.adoc[tag=match-insert1]
----


Fantastic - we've covered the basics of TypeQL!
You've seen how to manage databases and transactions, define schemas, and read and write data into TypeDB!

The next section will illustrate the power of TypeQL's clause chaining and show you how to modularize queries using functions.
