= Overview
:pageTitle: Overview
:Summary: Overview of get started guide
:keywords: start, learn, typedb, typeql, cloud, tutorial, quickstart, get-started, console, studio, database, create, insert, query, overview
:test-typeql: linear

This section features a step-by-step guide to getting started with TypeDB using a simple social-network
that includes people, friendships, employments, and organizations. You won't need to install anything - 
run TypeDB server in the cloud for free, and interact with it via the web-based TypeDB Studio

It is intended to give a quick rundown of the main interactions you'll have with TypeDB,
such as database management, schema definition, data loading, and composing multi-step queries.

== Mini-guide

The following outline serves both as an example of the main things you'll do with TypeDB,
and a quick outline of the following Get Started guide - if you just want to speed through right here you can, though we recommend following the full guide!

. xref:{page-version}@new_home::get_started/setup.adoc[]
.. Sign up & launch a free TypeDB instance on https://cloud.typedb.com[TypeDB Cloud account,window=_blank].
.. Follow the instructions from the cluster to open https://studio.typedb.com[TypeDB Studio,window=_blank].

. xref:{page-version}@new_home::get_started/schema.adoc[]
.. Create a database called `get_started`.
.. Execute a query to create the social network schema using a schema transaction:
+
[,typeql]
----
#!test[schema]
include::{page-version}@new_home::page$get_started/schema.adoc[tag=full_define]
----

. xref:{page-version}@new_home::get_started/data.adoc[]
.. Run a series of pure inserts using a write transaction:
+
[,typeql]
----
#!test[write]
include::{page-version}@new_home::page$get_started/data.adoc[tag=insert2]
----
+
[,typeql]
----
#!test[write]
include::{page-version}@new_home::page$get_started/data.adoc[tag=insert3]
----
+
[,typeql]
----
#!test[write]
include::{page-version}@new_home::page$get_started/data.adoc[tag=insert5]
----
.. Run a read-write query:
+
[,typeql]
----
#!test[write, count=1]
include::{page-version}@new_home::page$get_started/data.adoc[tag=match-insert1]
----

. Use your loaded schema and data to write aggregation queries, compose query pipelines, and create functions in xref:{page-version}@new_home::get_started/query-composition.adoc[]
