= Patterns
:page-aliases: {page-version}@typeql::patterns.adoc

This reference covers the usage of patterns in TypeQL.

== Scopes
Pattern comprise statements containing variables. Given a pattern, the *scope* of a variable is:

* the block `{ ... }` in which variable appears at top-level (i.e., not nested in further `{...}`) but it does not appear outside of the block.
* or, the entire pattern itself if the variable appears at the top-level of the pattern itself.

Exceptionally, if the variable appears in all branches of a disjunction, it counts as appearing in the parent pattern.

A key principle of valid TypeQL pattern is:

> *_Every variable must have a unique scope._*

== Combining patterns

TypeQL allows us to construct larger and more interesting patterns from smaller ones,
allowing us to express more than simple conjunctions.
They can also create new scopes of variables.

[cols-3]
--
.xref:{page-version}@typeql-reference::patterns/conjunctions.adoc[]
[.clickable]
****
Use of conjunctions to join patterns into a single query pattern that combines all given constraints.
****

.xref:{page-version}@typeql-reference::patterns/disjunction.adoc[]
[.clickable]
****
Use of disjunctions to allow for several branches in a query to be executed in parallel.
****

.xref:{page-version}@typeql-reference::patterns/negations.adoc[]
[.clickable]
****
Use of negations to exclude patterns from your query results.
****

.xref:{page-version}@typeql-reference::patterns/optionals.adoc[]
[.clickable]
****
Use of optionals for optionally matching subpatterns.
****
--