= TypeDB Studio
:page-aliases: {page-version}@manual::tools/studio.adoc

[.float-group]
--
TypeDB Studio is an interactive visual environment for managing and querying TypeDB databases.

With Studio, developers can efficiently manage databases, execute queries, and explore query results,
all within a unified environment.

This page provides a quick introduction to TypeDB Studio and an overview of its features. All features of TypeDB Studio
are available on both web and desktop. Be aware that the web app may not be able to connect to non-HTTPS endpoints (e.g. localhost, 127.0.0.1) on certain browsers; at the time of writing, Chrome works, but Safari does not.
--

[cols-2]
--
.https://studio.typedb.com[Visit studio.typedb.com]
[.clickable]
****
Launch TypeDB Studio in your web browser.
****

.https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name:%5Etypedb-studio[Install TypeDB Studio Desktop,window=_blank]
[.clickable]
****
Download TypeDB Studio for desktop.
****

.link:https://github.com/typedb/typedb-studio/[GitHub,window=_blank]
[.clickable]
****
Browse the source code of TypeDB Studio.
****
--

== Quickstart

=== Connect to TypeDB

Select TypeDB edition below, and follow the instructions:

include::{page-version}@home::partial$studio_connect.adoc[tag=connect_studio]

=== Select a database

To select a database to work with, use the dropdown menu on the right of the database icon in the top toolbar. You can also create new databases here.

TypeDB Studio will automatically select a *default* database if there are no others present.


== Query tool

You can run queries against the connected TypeDB server using TypeDB Studio's https://studio.typedb.com/query[query tool,window=_blank].

=== Write a query

You can write TypeQL queries in the Query pane.

The Query pane contains a code editor that offers TypeQL highlighting and autocompletion.

=== Run a query

When your query is ready to run, hit "Run query" in the Query pane.

Results are printed to the Results pane.

=== Query results

The Results pane offers three different views of results - you can choose between *Log*, *Table*, *Graph* and *Raw*.

The Log contains textual output, similar to TypeDB Console, as well as input log, and error messages.

Table view is well suited for visualising the answers of *match* and *fetch* queries in a tabular format, where each row represents an answer, and each column represents a variable.

Graph (network) output is appropriate for visualising and understanding the connections in your dataset.

Raw output allows you to see the raw HTTP response from TypeDB and is useful for debugging.

=== Schema pane

The Schema pane lists your schema objects and their capabilities - e.g. owned attributes and played roles.

It acts as a reference panel indicating what you can query.

You can configure its view mode (flat or hierarchical) by clicking the options button in its top bar. Flat layout is
typically better for simple schemas, while the hierarchical view is better for more complex schemas with subtyping.

The options pane also allows you to filter what capabilities are displayed. For example, you can set it to only display
owned attributes, or to only display roleplayers of relations.

You can also view the full schema text from this pane.

=== History pane

All queries and transaction operations are timestamped and logged to the History pane.
You can copy and replay queries from this pane.
Any errors that occur can be inspected from this pane.

=== Transaction controls

By default, transactions are fully managed by TypeDB Studio. A transaction opens when you start running a query, and commits when a schema/write query is done or closes when a read query is done.

For more fine-grained control, you can use the top bar to change the transaction mode from *auto* to *manual*. This allows you to open transactions, and perform multiple queries within a transaction before closing or committing.

Only one transaction can be open concurrently within a single instance of TypeDB Studio.

=== Connection management

To connect, disconnect, or change connection settings, use the connection button in the top bar.
While connected to TypeDB, the button changes its label to the server's address or the custom name provided when setting up the connection.

=== Error handling

Query-level errors are printed to Log Output. These are typically errors returned directly from TypeDB, and will contain detailed error codes and explanations of the problem (e.g: illegal TypeQL semantics)

Transaction-level errors will trigger an error popup notification.

Both types of errors can be viewed and copied to the clipboard by visiting the History pane on the Query page.


== Schema tool

TypeDB Studio's https://studio.typedb.com/schema[Schema tool,window=_blank] allows you to visualise your TypeDB schema.

It renders the entire schema as a graph visualisation, with nodes representing entities, relations, attributes, etc.,
and edges representing capabilities such as owned attributes and played roles.


== Data explorer

You can explore your TypeDB data without writing queries in the https://studio.typedb.com/data[Data explorer,window=_blank], an interactive visual environment for exploring data.

Select any type, and it will show you a table of instances and their most interesting connections - attributes, relations, roleplayers, etc.

Select any instance from that table, and you can see all its connections in greater detail, allowing you to see exactly what data you're looking at.

You can then jump to connected instances using the "Explore" buttons on instance details, and as such you can traverse your dataset entirely using this visual UI without needing to write queries.

=== Table of instances

Once you're in the data explorer, start exploring by selecting any type from the schema. This will bring up a table of instances of that type, as well as:

- For entities and relations: the instance's attributes;
- For entities and relations: a summary of the instance's relations;
- For relations: a summary of the instance's roleplayers;
- For attributes: the attribute's value and value type;
- The instance's type - as tables include subtypes of the selected type.

Selecting any instance from this table will take you to Instance Details.

Instance tables support standard table functionality (filtering, sorting, pagination, column picker ...) Filtering, sorting and pagination are all handled server-side using TypeQL queries.

=== Instance details

Instance details show the same info as tables in much more detail.
In particular, roleplayers, attribute owners and linked relations include their attributes so that data is clearly labelled.

You can jump to connected instances using the "Explore" buttons on instance details, allowing you to traverse your dataset.
Explorations leave behind a breadcrumb that indicates the exploration chain you've taken to get to a specific instance.
Thus, breadcrumbs form a chain of connected concepts.

Data Explorer tabs support standard tab functionality (close, close others, close all, pin ...) and are restored (but perform fresh queries) when you reopen TypeDB Studio.

=== Working with a data snapshot

In manual transaction mode the user can work with a fixed snapshot of their data for stable exploration.


== User manager

You can manage database users in TypeDB Studio's https://studio.typedb.com/users[User Manager,window=_blank].

The User Manager allows you to view, create, update, and delete users. It lists all users in a table view.

=== Create a new user

To create a new user, click the "Create user" button in the User Manager.

=== Change a user's password

To change a user's password, click the "Change password" button in the row corresponding to that user.

=== Delete a user

To delete a user, click the "Delete user" button in the row corresponding to that user.
