= Undefine query
:page-aliases: {page-version}@reference::typeql/queries/undefine.adoc
:test-typeql: linear

Undefine queries are used
// tag::overview[]
to remove existing types, constraints, or functions from the schema.
// end::overview[]

== Syntax

Undefine queries start with the `undefine` keyword following by undefinition statements.

[,typeql]
----
undefine
  <undefinition_statements>
----

Undefinition statements are similar to definition statements, but they have a different structure to highlight which part of the definition is to be undefined, in some cases using the `from` keyword.

.Type undefinition statement
[,typeql]
----
<label>;
----

.interface undefinition statement
[,typeql]
----
<interface_definition> from <type_label>;
----

.Annotation undefinition statement
[,typeql]
----
<@annotation> from <type_label_or_interface>;
----

.Function undefinition statement
[,typeql]
----
fun <function name>;
----

Statements should be separated by semicolons.
Schema statements in an undefine query cannot use variables or values.

== Behavior

An undefine query removes the parts of the schema specified in its undefine clause, including types, interfaces, annotations, and functions.
Undefining a type also undefines all its interfaces and annotations.
Undefining a interface also undefines all its interfaces and annotations.

An error is returned (on execution or on commit), and no changes are preserved, if:

- There is no existing definition to undefine.
- The query results in an invalid schema.

[#_statements_behavior]
=== Statements

* xref:{page-version}@typeql-reference::statements/relates.adoc[`relates ... from` statements] undefine existing relates and role types.
* xref:{page-version}@typeql-reference::statements/relates.adoc[`as ... from relates` statements] undefine existing relates specializations.
* xref:{page-version}@typeql-reference::statements/plays.adoc[`plays ... from` statements] undefine existing roleplayings.
* xref:{page-version}@typeql-reference::statements/owns.adoc[`owns ... from` statements] undefine existing ownerships.
* xref:{page-version}@typeql-reference::statements/value.adoc[`value ... from` statements] undefine existing attribute types' value types.
* xref:{page-version}@typeql-reference::statements/sub.adoc[`sub ... from` statements] undefine existing subtyping connections.
* xref:{page-version}@typeql-reference::annotations/index.adoc[`@annotation ... from` statements] undefine existing annotations.
Only the type of the annotation is required, so annotations with arguments can be undefined without their arguments specification.
* xref:{page-version}@typeql-reference::statements/fun.adoc[`fun ...` statements] undefine existing functions.

== Examples

.Schema for the following examples
[%collapsible]
====
[,typeql]
----
#!test[schema, commit]
include::{page-version}@reference::example$tql/schema_statements_functions.tql[tags=define-keyword;entities;attributes;extended-attributes]
attribute tag value string;
entity post owns tag @card(0..);
relation parentship @abstract, relates parent, relates child;
relation fathership sub parentship, relates father as parent;
user plays parentship:parent;
user owns email @card(0..1);
----
====

=== Undefining types

.Undefining a type
[,typeql]
----
#!test[schema, rollback]
undefine user;
----

.Undefining types
[,typeql]
----
#!test[schema, rollback]
undefine fathership; email;
----

=== Undefining interfaces

.Undefining relation type's relates
[,typeql]
----
#!test[schema]
undefine relates child from parentship;
----

.Undefining relates specialization
[,typeql]
----
#!test[schema]
undefine as parent from fathership relates father;
----

.Undefining relation type's subtyping
[,typeql]
----
#!test[schema]
# Note, this requires the specialisation to have been undefined first.
undefine sub parentship from fathership;
----

.Undefining type's roleplaying
[,typeql]
----
#!test[schema]
undefine plays parentship:parent from user;
----

.Undefining attribute type's value type
[,typeql]
----
#!test[schema, fail_at=runtime]
undefine value string from email;
----

.Undefining type's ownership
[,typeql]
----
#!test[schema, rollback]
undefine owns email from user;
----

=== Undefining annotations

.Undefining type's annotation without arguments
[,typeql]
----
#!test[schema]
undefine @abstract from parentship;
----

.Undefining value type's annotation with arguments
[,typeql]
----
#!test[schema]
undefine @regex from email value string;
----

.Undefining type's and type's ownership's annotations
[,typeql]
----
#!test[schema]
undefine
  @card from user owns email;
  @independent from email;
----

=== Undefining functions

include::{page-version}@reference::typeql/functions/writing.adoc[tag=undefine]
